version: '3'

services:
  api_gateway:
    build: ./api_gateway
    links: 
      - users_service
      - auth_service
    ports:
      - "8080:3000"

  users_service:
    build: ./users_service
    links:
      - showreel_mysql_db
    ports:
      - "8081:8081"

  auth_service:
    build: ./auth_service
    links:
      - showreel_mysql_db
    ports:
      - "8082:8082"

  showreel_mysql_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=showreel
    volumes:
      - ./showreel_mysql_db:/docker-entrypoint-initdb.d

    # Ports explanation: First port is external public port for access from your machine, like using CURL or Postman etc ...
    # Second port is the port of the container itself, and it's used by other containers to communicate.
    # Check in other services dbconfig.go files, they connect to 3306 since they're within the same network
    ports:
      - "3308:3306"

volumes:
    db_data: